export const UPDATE_CURRENCY = 'UPDATE_CURRENCY';

export const FETCH_MARKET_COINS_REQUEST = 'FETCH_MARKET_COINS_REQUEST';
export const FETCH_MARKET_COINS_SUCCESS = 'FETCH_MARKET_COINS_SUCCESS';
export const FETCH_MARKET_COINS_FAILURE = 'FETCH_MARKET_COINS_FAILURE';

